import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "@/_styles/globals.css";

const notoSans = Noto_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Swift Tool Hire",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSans} antialiased`}>{children}</body>
    </html>
  );
}
